---
- name: check for mounted disk
  shell: "grep '{{ gentoo_install_disk }}' /proc/mounts"
  failed_when: false
  changed_when: false
  register: check_mounted_disk
  check_mode: no

- name: abort if disk mounted
  fail:
    msg: "Aborting install due to {{ gentoo_install_disk }} being mounted"
  when: check_mounted_disk.rc == 0

- name: create disklabel
  command: >
    parted --align optimal --script {{ gentoo_install_disk }}
      mklabel {{ gentoo_install_disklabel }}
      --
      unit mib
      mkpart primary 1 3
      name 1 grub
      set 1 bios_grub on
      mkpart primary 3 131
      name 2 boot
      set 2 boot on
      mkpart primary 131 643
      name 3 swap
      mkpart primary 643 -1
      name 4 rootfs


- name: format boot partition
  filesystem: dev={{ gentoo_install_disk }}1 fstype=vfat force=yes

- name: format boot partition
  filesystem: dev={{ gentoo_install_disk }}2 fstype=ext2 force=yes

- name: format swap partition
  filesystem: dev={{ gentoo_install_disk}}3 fstype=swap force=yes

- name: mount swap
  command: "swapon {{ gentoo_install_disk}}3"

- name: format root partition
  filesystem: dev={{ gentoo_install_disk }}4 fstype=btrfs force=yes

- name: mount root partition
  mount:
    name: /mnt/gentoo
    src: "{{ gentoo_install_disk }}4"
    fstype: btrfs
    state: mounted

- name: create /boot mountpoint
  file:
    path: /mnt/gentoo/boot
    state: directory

- name: mount boot partition
  mount:
    name: /mnt/gentoo/boot
    src: "{{ gentoo_install_disk }}2"
    fstype: ext2
    state: mounted
    
- name: create /boot/efi mountpoint
  file:
    path: /mnt/gentoo/boot/efi
    state: directory

- name: mount boot partition
  mount:
    name: /mnt/gentoo/boot/efi
    src: "{{ gentoo_install_disk }}1"
    fstype: vfat
    state: mounted
