---
- name: install prebuild binary kernel
  portage:
    package: gentoo-kernel-bin
    state: installed

- name: append USE-Flags for linux-firmware to package.license
  lineinfile:
    path: /etc/portage/package.license
    line: "sys-kernel/linux-firmware linux-fw-redistributable no-source-code"
    create: yes

- name: install firmware
  portage:
    package: sys-kernel/linux-firmware
    state: installed

